import json
from qdrant_client import QdrantClient, models

# --- Configuration ---
QDRANT_HOST = "localhost"
QDRANT_PORT = 6333 # REST API port
COLLECTION_NAME = "my_documents"
VECTOR_SIZE = 384 # This should match the output dimension of your SentenceTransformer model

# --- Load Vectors from File ---
try:
    with open('vectors.json', 'r') as f:
        vectors_data = json.load(f)
except FileNotFoundError:
    print("Error: vectors.json not found. Please run generate_vectors.py first.")
    exit()

# --- Initialize Qdrant Client ---
client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

# --- Create Collection (if it doesn't exist) ---
# It's good practice to ensure the collection exists and has the correct configuration
try:
    client.recreate_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=models.VectorParams(size=VECTOR_SIZE, distance=models.Distance.COSINE),
    )
    print(f"Collection '{COLLECTION_NAME}' recreated successfully (or created if it didn't exist).")
except Exception as e:
    print(f"Error creating/recreating collection: {e}")
    # If recreate fails (e.g., due to existing collection with different config),
    # you might want to try client.get_collection or client.delete_collection first
    print("Attempting to get collection info in case it already exists...")
    try:
        collection_info = client.get_collection(collection_name=COLLECTION_NAME)
        print(f"Collection '{COLLECTION_NAME}' already exists with config: {collection_info.config}")
    except Exception as get_e:
        print(f"Could not get collection info either: {get_e}")
        exit()


# --- Prepare Points for Upload ---
points = []
for item in vectors_data:
    points.append(
        models.PointStruct(
            id=item["id"],
            vector=item["vector"],
            payload=item["payload"]
        )
    )

# --- Upload Points to Qdrant ---
try:
    operation_info = client.upsert(
        collection_name=COLLECTION_NAME,
        wait=True, # Wait for the operation to be completed
        points=points
    )
    print(f"Successfully uploaded {len(points)} vectors to Qdrant.")
    print(f"Operation info: {operation_info}")
except Exception as e:
    print(f"Error uploading vectors: {e}")

# --- Verify (Optional) ---
try:
    count_result = client.count(
        collection_name=COLLECTION_NAME,
        exact=True # Get exact count
    )
    print(f"Total vectors in collection '{COLLECTION_NAME}': {count_result.count}")
except Exception as e:
    print(f"Error getting collection count: {e}")

# --- Perform a sample search (Optional) ---
print("\n--- Performing a sample search ---")
query_text = "What is a vector database?"
query_vector = model.encode(query_text).tolist() # Reuse the model from your previous script

try:
    search_result = client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_vector,
        limit=2, # Get top 2 results
        with_payload=True # Include the original text in the results
    )
    print(f"Search results for '{query_text}':")
    for hit in search_result:
        print(f"  ID: {hit.id}, Score: {hit.score:.4f}, Text: {hit.payload['text']}")
except Exception as e:
    print(f"Error during search: {e}")

"""
**Explanation of the Upload Script:**

1. **Import necessary libraries:** `json` for reading your data and `qdrant_client` for interacting with Qdrant.
2. **Configuration:**
    - `QDRANT_HOST` and `QDRANT_PORT`: These should match the host and port where your Dockerized Qdrant instance is running (usually `localhost:6333`).
    - `COLLECTION_NAME`: This is the name you'll give to your collection of vectors in Qdrant. You can choose any descriptive name.
    - `VECTOR_SIZE`: **Crucially, this must match the dimension of the embeddings generated by your `SentenceTransformer` model (which was 384 for `all-MiniLm-L6-v2`).**
3. **Load Vectors:** It reads your `vectors.json` file.
4. **Initialize Client:** Creates an instance of `QdrantClient` to connect to your Qdrant server.
5. **Create Collection:**
    - `client.recreate_collection()`: This is a convenient method. If the collection doesn't exist, it creates it. If it *does* exist, it will delete and then recreate it. This is often useful during development to start fresh.
    - `vectors_config`: Defines the properties of the vectors in this collection.
        - `size`: The dimension of your vectors (384).
        - `distance`: The metric used to calculate similarity between vectors. `COSINE` (cosine similarity) is very common and works well for many text embeddings. Other options include `EUCLID` (Euclidean distance) or `DOT` (dot product).
6. **Prepare Points:** It iterates through your `vectors_data` and converts each entry into a `models.PointStruct`. A "point" in Qdrant represents a single vector entry, consisting of:
    - `id`: A unique identifier for the point.
    - `vector`: The actual numerical embedding.
    - `payload`: A dictionary of associated metadata (like your original `text`). This is super useful for filtering and displaying results.
7. **Upload Points (`upsert`):**
    - `client.upsert()`: This method is used to insert or update points in a collection.
    - `wait=True`: Ensures the script waits until the upload operation is completed by Qdrant before proceeding.
8. **Verify (Optional but Recommended):**
    - `client.count()`: Checks how many vectors are now in your collection, confirming the upload.
9. **Perform a Sample Search (Optional):**
    - To demonstrate searching, it takes a new query text.
    - It uses your `model.encode()` again to convert the query text into a vector. **You will need to ensure the `model` object from your `generate_vectors.py` script is available here, or re-load it if you run this script separately.** I've added a note in the code for this.
    - `client.search()`: Performs the similarity search.
        - `query_vector`: The embedding of your search query.
        - `limit`: How many top similar results you want.
        - `with_payload=True`: Tells Qdrant to return the original text (from the `payload`) along with the vector results.

**What to Expect:**

- You'll see output confirming the collection creation/recreation.
- Messages about the successful upload of vectors.
- The total count of vectors in your collection (should be 3 in your case).
- If the search part is included, you'll see the results of your sample similarity search, showing which of your original documents are most similar to your query.
"""